### ISSUE TITLE
bug about **single line** svg output

### ISSUE THREAD

**Issue by junjieim** [javierbyte/pintr#3]
1. test img:
![plan](https://user-images.githubusercontent.com/48527686/143538828-34bb53fc-eaed-4be2-82c7-a987a25b158a.jpg)

2. what it shown before download:
![image](https://user-images.githubusercontent.com/48527686/143538857-039bfd9c-f9bb-44c9-842d-1e6daba0bae6.png)

3. what it actually shown in svg file:
![image](https://user-images.githubusercontent.com/48527686/143538965-e0dfb7d5-cbb0-4922-85e1-c9f4f128cd87.png)

env: win10 + chrome

thx!

**Comment by junjieim** [comment]
It seems to have been fixed in `f097401`.

**Comment by javierbyte** [comment]
@junjieim yes! it is fixed now, thank you! :)
